<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <Version>0.2.5</Version>
    <AssemblyVersion>0.2.5.0</AssemblyVersion>
    <FileVersion>0.2.5.0</FileVersion>
    <Product>Patchouli.Net</Product>
    <Title>Patchouli.Net</Title>
    <AssemblyTitle>Patchouli.Net</AssemblyTitle>
  </PropertyGroup>
</Project>
