using Patchouli.Core.Ids;
using Patchouli.Infrastructure.Snapshots;

namespace Patchouli.UI;
public sealed class SnapshotBranchViewModel : ViewModelBase
{
    private readonly MainWindowViewModel _main; private SnapshotBranchInspectionInfo? _branch; private BranchImportPlan? _plan;
    public string ManifestPath { get; set; } = ""; public string StagingRoot { get; set; } = ""; public string SelectedItemIds { get; set; } = ""; public string SelectedDocumentIds { get; set; } = ""; public bool ConfirmImport { get; set; } public string DestinationPath { get; set; } = ""; public string Output { get; private set; } = "No automatic merge. No silent last-writer-wins. Credentials and original files are not imported.";
    public AsyncCommand OpenCommand { get; } public AsyncCommand ListItemsCommand { get; } public AsyncCommand BuildPlanCommand { get; } public AsyncCommand ApplyCommand { get; } public AsyncCommand DiscardCommand { get; } public AsyncCommand KeepCopyCommand { get; }
    public SnapshotBranchViewModel(MainWindowViewModel main){_main=main;OpenCommand=new(OpenAsync);ListItemsCommand=new(ListAsync);BuildPlanCommand=new(BuildAsync);ApplyCommand=new(ApplyAsync);DiscardCommand=new(DiscardAsync);KeepCopyCommand=new(KeepAsync);}
    private async Task OpenAsync(){var r=await (await _main.ServicesAsync()).BranchInspection.OpenBranchForInspectionAsync(ManifestPath,StagingRoot);if(r.IsSuccess)_branch=r.Value;Output=r.IsSuccess?System.Text.Json.JsonSerializer.Serialize(r.Value,new System.Text.Json.JsonSerializerOptions{WriteIndented=true}):$"ERROR {r.ErrorCode}: {r.ErrorMessage}";Raise(nameof(Output));}
    private async Task ListAsync(){if(_branch is null){Output="ERROR invalid_state: Open a branch first.";}else{var r=await (await _main.ServicesAsync()).BranchInspection.ListBranchItemsAsync(_branch);Output=r.IsSuccess?System.Text.Json.JsonSerializer.Serialize(r.Value,new System.Text.Json.JsonSerializerOptions{WriteIndented=true}):$"ERROR {r.ErrorCode}: {r.ErrorMessage}";}Raise(nameof(Output));}
    private async Task BuildAsync(){if(_branch is null){Output="ERROR invalid_state: Open a branch first.";}else{try{var items=SelectedItemIds.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Select(ItemId.Parse).ToArray();var docs=SelectedDocumentIds.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Select(DocumentInstanceId.Parse).ToArray();var r=await (await _main.ServicesAsync()).BranchInspection.BuildImportPlanAsync(_branch,items,docs);if(r.IsSuccess)_plan=r.Value;Output=r.IsSuccess?System.Text.Json.JsonSerializer.Serialize(r.Value,new System.Text.Json.JsonSerializerOptions{WriteIndented=true}):$"ERROR {r.ErrorCode}: {r.ErrorMessage}";}catch(Exception ex){Output=$"ERROR validation_failed: {ex.Message}";}}Raise(nameof(Output));}
    private async Task ApplyAsync(){if(_plan is null){Output="ERROR invalid_state: Build an import plan first.";}else{var r=await (await _main.ServicesAsync()).BranchInspection.ApplyImportPlanAsync(_plan,ConfirmImport);Output=r.IsSuccess?System.Text.Json.JsonSerializer.Serialize(r.Value,new System.Text.Json.JsonSerializerOptions{WriteIndented=true}):$"ERROR {r.ErrorCode}: {r.ErrorMessage}";}Raise(nameof(Output));}
    private async Task DiscardAsync(){if(_branch is null){Output="ERROR invalid_state: Open a branch first.";}else{var r=await (await _main.ServicesAsync()).BranchInspection.DiscardBranchAsync(_branch);Output=r.IsSuccess?"Branch staging copy discarded; active runtime DB was not touched.":$"ERROR {r.ErrorCode}: {r.ErrorMessage}";}Raise(nameof(Output));}
    private async Task KeepAsync(){if(_branch is null){Output="ERROR invalid_state: Open a branch first.";}else{var r=await (await _main.ServicesAsync()).BranchInspection.KeepBranchAsSeparateLibraryCopyAsync(_branch,DestinationPath);Output=r.IsSuccess?$"Branch copy created: {r.Value}. Active runtime DB was not touched.":$"ERROR {r.ErrorCode}: {r.ErrorMessage}";}Raise(nameof(Output));}
}
