using LiteratureApp.Core.Ids;
using LiteratureApp.Core.Results;
using LiteratureApp.Core.Time;

namespace LiteratureApp.Ocr;
public sealed class OcrRetryPolicy : IOcrRetryPolicy
{
    private static readonly HashSet<string> Transient=["network_timeout","temporary_provider_error","rate_limited","quota_exceeded_retryable","worker_crashed",OcrFailureCode.LocalOcrTimeout];
    private static readonly HashSet<string> Manual=["auth_failed","model_not_found","bad_endpoint_config","model_path_missing","model_path_inaccessible",OcrFailureCode.SourceFileMissing,OcrFailureCode.SourceFileChanged,OcrFailureCode.BBoxCoordinateTransformFailed,OcrFailureCode.ImageTooLargeForOcr,OcrFailureCode.RendererTimeout,"unsupported_file","invalid_page_box","missing_executable"];
    public string Classify(string? code)=>Manual.Contains(code??"")?OcrRetryClassification.ManualRepairRequired:Transient.Contains(code??"")?OcrRetryClassification.TransientRetryable:OcrRetryClassification.NonRetryable;
    public bool ShouldRetry(OcrQueueTask task,string? code)=>Classify(code)==OcrRetryClassification.TransientRetryable&&(code==OcrFailureCode.LocalOcrTimeout?task.AttemptCount<1:task.AttemptCount<task.MaxAttempts);
    public TimeSpan GetNextDelay(int attempt)=>attempt switch{1=>TimeSpan.FromSeconds(5),2=>TimeSpan.FromSeconds(30),_=>TimeSpan.FromMinutes(2)};
}
public sealed class OcrQueueScheduler : IOcrQueueScheduler
{
    private readonly IClock _clock; private readonly IOcrQueueTaskExecutor _executor; private readonly IOcrRetryPolicy _retry; private readonly OcrQueueLimits _limits; private readonly Dictionary<OcrQueueTaskId,OcrQueueTask> _tasks=new(); private readonly HashSet<string> _pauses=new(); private readonly Dictionary<OcrQueueTaskId,CancellationTokenSource> _running=new(); private readonly SemaphoreSlim _gate=new(1,1); private readonly LibraryId _libraryId; private readonly Action<Exception>? _loopErrorLogger; private readonly TimeSpan _loopInterval; private CancellationTokenSource? _loop; private Task? _loopTask;
    public OcrQueueScheduler(LibraryId libraryId,IClock clock,IOcrQueueTaskExecutor executor,IOcrRetryPolicy? retry=null,OcrQueueLimits? limits=null,TimeSpan? loopInterval=null,Action<Exception>? loopErrorLogger=null){_libraryId=libraryId;_clock=clock;_executor=executor;_retry=retry??new OcrRetryPolicy();_limits=limits??OcrQueueLimits.Default;_loopInterval=loopInterval??TimeSpan.FromMilliseconds(500);_loopErrorLogger=loopErrorLogger;}
    public Task<Result<OcrQueueTask>> EnqueueMockPagesAsync(DocumentInstanceId d,OcrPresetId p,IReadOnlyList<PageId> pages,string priority,CancellationToken c=default)=>EnqueueAsync(new(d,p,pages,OcrQueueTaskKind.MockPages,OcrEngineIds.Mock,OcrAdapterKind.Mock,null,priority),c);
    public Task<Result<OcrQueueTask>> EnqueueImagePageAsync(DocumentInstanceId d,OcrPresetId p,PageId page,string path,string priority,CancellationToken c=default)=>EnqueueAsync(new(d,p,[page],OcrQueueTaskKind.ImagePage,OcrEngineIds.TesseractCli,OcrAdapterKind.LocalProcess,null,priority,path),c);
    public Task<Result<OcrQueueTask>> EnqueueRenderedPdfPageAsync(DocumentInstanceId d,OcrPresetId p,PageId page,int dpi,string priority,CancellationToken c=default)=>EnqueueAsync(new(d,p,[page],OcrQueueTaskKind.RenderedPdfPage,OcrEngineIds.TesseractCli,OcrAdapterKind.LocalProcess,null,priority,null,dpi),c);
    public Task StartAsync(CancellationToken c=default){if(_loopTask is { IsCompleted:false})return Task.CompletedTask;_loop=CancellationTokenSource.CreateLinkedTokenSource(c);_loopTask=Task.Run(async()=>{while(!_loop.IsCancellationRequested){try{await RunOneSchedulingTickAsync(_loop.Token);}catch(OperationCanceledException) when(_loop.IsCancellationRequested){}catch(Exception ex){try{_loopErrorLogger?.Invoke(ex);}catch{}}try{await Task.Delay(_loopInterval,_loop.Token);}catch(OperationCanceledException) when(_loop.IsCancellationRequested){}}},CancellationToken.None);return Task.CompletedTask;}
    public async Task StopAsync(CancellationToken c=default){if(_loop is null)return;_loop.Cancel();try{if(_loopTask is not null)await _loopTask;}catch(OperationCanceledException){}finally{_loop.Dispose();_loop=null;_loopTask=null;}}
    public async Task<Result<OcrQueueTask>> EnqueueAsync(OcrQueueTaskRequest request,CancellationToken c=default){if(request.PageIds.Count==0||string.IsNullOrWhiteSpace(request.TaskKind)||string.IsNullOrWhiteSpace(request.EngineId)||string.IsNullOrWhiteSpace(request.AdapterKind))return Result<OcrQueueTask>.Failure(AppErrorCodes.ValidationFailed,"OCR queue task requires pages, kind, engine, and adapter kind.");await _gate.WaitAsync(c);try{var n=_clock.UtcNow;var t=new OcrQueueTask(OcrQueueTaskId.New(),_libraryId,request.DocumentInstanceId,request.PresetId,request.PageIds,request.TaskKind,request.EngineId,request.AdapterKind,request.ProviderId,request.Priority,n,n,OcrQueueTaskState.Queued,0,Math.Max(1,request.MaxAttempts),null,null,null,null,request.ImagePath,request.Dpi);_tasks[t.TaskId]=t;return Result<OcrQueueTask>.Success(t);}finally{_gate.Release();}}
    public async Task RunOneSchedulingTickAsync(CancellationToken c=default){OcrQueueTask? task=null;CancellationTokenSource? cts=null;await _gate.WaitAsync(c);try{task=_tasks.Values.Where(t=>t.State==OcrQueueTaskState.Queued&&(t.ScheduledAfter is null||t.ScheduledAfter<=_clock.UtcNow)&&!Paused(t)&&CanRun(t)).OrderByDescending(Score).ThenBy(t=>t.CreatedAt).FirstOrDefault();if(task is null)return;task=task with{State=OcrQueueTaskState.Running,UpdatedAt=_clock.UtcNow};_tasks[task.TaskId]=task;cts=new CancellationTokenSource();_running[task.TaskId]=cts;}finally{_gate.Release();}OcrQueueExecutionResult r;try{r=await _executor.ExecuteAsync(task,cts.Token);}catch(OperationCanceledException){r=new(false,true);}catch(Exception ex){try{_loopErrorLogger?.Invoke(ex);}catch{}r=new(false,false,"worker_crashed",ex.Message);}await _gate.WaitAsync(c);try{_running.Remove(task.TaskId);var now=_clock.UtcNow;if(r.Cancelled)_tasks[task.TaskId]=task with{State=OcrQueueTaskState.Cancelled,UpdatedAt=now};else if(r.Succeeded)_tasks[task.TaskId]=task with{State=OcrQueueTaskState.Succeeded,UpdatedAt=now};else if(_retry.ShouldRetry(task,r.ErrorCode))_tasks[task.TaskId]=task with{State=OcrQueueTaskState.Queued,AttemptCount=task.AttemptCount+1,ScheduledAfter=now+_retry.GetNextDelay(task.AttemptCount+1),LastErrorCode=r.ErrorCode,LastErrorMessage=r.ErrorMessage,UpdatedAt=now};else _tasks[task.TaskId]=task with{State=_retry.Classify(r.ErrorCode)==OcrRetryClassification.ManualRepairRequired?OcrQueueTaskState.Blocked:OcrQueueTaskState.Failed,LastErrorCode=r.ErrorCode,LastErrorMessage=r.ErrorMessage,UpdatedAt=now};}finally{cts.Dispose();_gate.Release();}}
    public async Task<Result> PauseAsync(string scope,string? target=null,CancellationToken c=default){if(scope=="preset")return Result.Failure(AppErrorCodes.UnsupportedOperation,"Preset-level pause is not supported.");await _gate.WaitAsync(c);try{_pauses.Add(scope+":"+(target??""));return Result.Success();}finally{_gate.Release();}}
    public async Task<Result> ResumeAsync(string scope,string? target=null,CancellationToken c=default){await _gate.WaitAsync(c);try{_pauses.Remove(scope+":"+(target??""));return Result.Success();}finally{_gate.Release();}}
    public async Task<Result> CancelTaskAsync(OcrQueueTaskId id,CancellationToken c=default){await _gate.WaitAsync(c);try{if(!_tasks.TryGetValue(id,out var t))return Result.Failure(AppErrorCodes.NotFound,"Queue task was not found.");if(_running.TryGetValue(id,out var cts))cts.Cancel();else _tasks[id]=t with{State=OcrQueueTaskState.Cancelled,UpdatedAt=_clock.UtcNow};return Result.Success();}finally{_gate.Release();}}
    public Task<Result<OcrQueueTask>> GetTaskAsync(OcrQueueTaskId id,CancellationToken c=default)=>Task.FromResult(_tasks.TryGetValue(id,out var t)?Result<OcrQueueTask>.Success(t):Result<OcrQueueTask>.Failure(AppErrorCodes.NotFound,"Queue task was not found."));
    public Task<Result<IReadOnlyList<OcrQueueTask>>> ListTasksAsync(OcrQueueTaskFilter f,CancellationToken c=default)=>Task.FromResult(Result<IReadOnlyList<OcrQueueTask>>.Success(_tasks.Values.Where(t=>(f.State is null||t.State==f.State)&&(f.EngineId is null||t.EngineId==f.EngineId)&&(f.ProviderId is null||t.ProviderId==f.ProviderId)&&(f.IncludeCompleted||t.State is OcrQueueTaskState.Queued or OcrQueueTaskState.Running or OcrQueueTaskState.Paused)).OrderByDescending(Score).ToArray()));
    public Task<Result<OcrQueueStatus>> GetQueueStatusAsync(CancellationToken c=default){int C(string s)=>_tasks.Values.Count(t=>t.State==s);var r=_tasks.Values.Where(t=>t.State==OcrQueueTaskState.Running).ToArray();return Task.FromResult(Result<OcrQueueStatus>.Success(new(_loopTask is {IsCompleted:false},C(OcrQueueTaskState.Queued),C(OcrQueueTaskState.Running),C(OcrQueueTaskState.Succeeded),C(OcrQueueTaskState.Failed),C(OcrQueueTaskState.Cancelled),C(OcrQueueTaskState.Blocked),_pauses.ToArray(),_limits,r.GroupBy(t=>t.EngineId).ToDictionary(g=>g.Key,g=>g.Count()),r.Where(t=>t.ProviderId is not null).GroupBy(t=>t.ProviderId!).ToDictionary(g=>g.Key,g=>g.Count()))));}
    private bool Paused(OcrQueueTask t)=>_pauses.Contains("global:")||_pauses.Contains("task:"+t.TaskId)||(_pauses.Contains("local:")&&t.AdapterKind!=OcrAdapterKind.CloudApi)||(_pauses.Contains("cloud:")&&t.AdapterKind==OcrAdapterKind.CloudApi)||(!string.IsNullOrEmpty(t.ProviderId)&&_pauses.Contains("provider:"+t.ProviderId));
    private bool CanRun(OcrQueueTask t){var running=_tasks.Values.Where(x=>x.State==OcrQueueTaskState.Running).ToArray();if(running.Length>=_limits.GlobalMaxConcurrent)return false;var local=t.AdapterKind!=OcrAdapterKind.CloudApi;if(local&&running.Count(x=>x.AdapterKind!=OcrAdapterKind.CloudApi)>=_limits.LocalMaxConcurrent)return false;if(!local&&running.Count(x=>x.AdapterKind==OcrAdapterKind.CloudApi)>=_limits.CloudMaxConcurrent)return false;if(running.Count(x=>x.EngineId==t.EngineId)>=_limits.PerEngineMaxConcurrent)return false;if(t.ProviderId is not null&&running.Count(x=>x.ProviderId==t.ProviderId)>=_limits.PerProviderMaxConcurrent)return false;return true;}
    private int Score(OcrQueueTask t)=>Priority(t.Priority)*1000+(int)Math.Min(999,(_clock.UtcNow-t.CreatedAt).TotalMinutes/10);
    private static int Priority(string p)=>p switch{OcrQueuePriority.InteractiveCurrentPage=>6,OcrQueuePriority.InteractiveSelectedPages=>5,OcrQueuePriority.UserStartedDocument=>4,OcrQueuePriority.BackgroundRetry=>3,OcrQueuePriority.BatchCollection=>2,_=>1};
}
