<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Patchouli.Core\Patchouli.Core.csproj" />
    <ProjectReference Include="..\Patchouli.Search\Patchouli.Search.csproj" />
    <ProjectReference Include="..\Patchouli.Evidence\Patchouli.Evidence.csproj" />
  </ItemGroup>
</Project>
