using Dapper;
using LiteratureApp.Core.Ids;
using LiteratureApp.Core.Library;
using LiteratureApp.Core.Results;
using LiteratureApp.Infrastructure.Database;

namespace LiteratureApp.Infrastructure.Snapshots;

public sealed record SnapshotBranchInspectionInfo(string BranchId, LibraryId LibraryId, string SnapshotId, string? ParentSnapshotId, string? LocalCurrentSnapshotId, string DeviceId, DateTimeOffset CreatedAt, string ManifestPath, string StagingDatabasePath, bool IsLibraryMatch, bool IsCurrentParentMismatch, IReadOnlyList<string> Warnings);
public sealed record BranchItemSummary(ItemId ItemId, string Title, string ItemType, string? Date, string CreatorSummary, int DocumentInstanceCount, bool HasOcr, bool HasSearchUnits, bool HasEvidenceRefs, string? Warning);
public sealed record BranchDocumentInstanceSummary(DocumentInstanceId DocumentInstanceId, ItemId ItemId, string? Title, string InstanceType, bool IsPrimary, int PageCount, int LayoutRevisionCount, int SearchUnitCount, int EvidenceRefCount, string SourceFileStatus, string? Warning);
public sealed record BranchImportConflict(string ObjectType, string SourceId, string? TargetId, string ConflictType, string RecommendedAction);
public sealed record BranchImportPlan(string PlanId, SnapshotBranchInspectionInfo SourceBranch, LibraryId TargetLibraryId, IReadOnlyList<ItemId> ItemsToImport, IReadOnlyList<DocumentInstanceId> DocumentInstancesToImport, int PagesToImport, int LayoutRevisionsToImport, int SearchUnitsToImport, int EvidenceRefsToImport, int FileAssetsToImport, IReadOnlyList<BranchImportConflict> Conflicts, IReadOnlyList<string> Warnings, bool RequiresUserConfirmation);
public sealed record BranchImportResult(bool Applied, int ImportedItems, int ImportedDocuments, int ImportedPages, int ImportedSearchUnits, int ImportedEvidenceRefs, IReadOnlyList<BranchImportConflict> UnresolvedConflicts, IReadOnlyList<string> Warnings, IReadOnlyList<DocumentInstanceId> DocumentsRequiringFtsRebuild);

public interface ISnapshotBranchInspectionService
{
    Task<Result<SnapshotBranchInspectionInfo>> OpenBranchForInspectionAsync(string manifestPath, string stagingRoot, CancellationToken cancellationToken = default);
    Task<Result<IReadOnlyList<BranchItemSummary>>> ListBranchItemsAsync(SnapshotBranchInspectionInfo branch, CancellationToken cancellationToken = default);
    Task<Result<IReadOnlyList<BranchDocumentInstanceSummary>>> ListBranchDocumentInstancesAsync(SnapshotBranchInspectionInfo branch, ItemId? itemId = null, CancellationToken cancellationToken = default);
    Task<Result<BranchImportPlan>> BuildImportPlanAsync(SnapshotBranchInspectionInfo branch, IReadOnlyList<ItemId> itemIds, IReadOnlyList<DocumentInstanceId> documentIds, CancellationToken cancellationToken = default);
    Task<Result<BranchImportResult>> ApplyImportPlanAsync(BranchImportPlan plan, bool userConfirmed, CancellationToken cancellationToken = default);
    Task<Result> DiscardBranchAsync(SnapshotBranchInspectionInfo branch, CancellationToken cancellationToken = default);
    Task<Result<string>> KeepBranchAsSeparateLibraryCopyAsync(SnapshotBranchInspectionInfo branch, string destinationPath, CancellationToken cancellationToken = default);
}

public sealed class SnapshotBranchInspectionService : ISnapshotBranchInspectionService
{
    private readonly ISnapshotImporter _importer; private readonly SqliteConnectionFactory _target; private readonly ILibraryIdentityService _library;
    public SnapshotBranchInspectionService(ISnapshotImporter importer, SqliteConnectionFactory target, ILibraryIdentityService library) { _importer = importer; _target = target; _library = library; }

    public async Task<Result<SnapshotBranchInspectionInfo>> OpenBranchForInspectionAsync(string manifestPath, string stagingRoot, CancellationToken ct = default)
    {
        var local = await _library.GetCurrentLibraryAsync(ct); if (local.IsFailure) return Result<SnapshotBranchInspectionInfo>.Failure(local.ErrorCode!, local.ErrorMessage!);
        var validation = await _importer.ValidateSnapshotAsync(manifestPath, ct); if (validation.IsFailure || !validation.Value.IsValid || validation.Value.Manifest is null) return Result<SnapshotBranchInspectionInfo>.Failure(AppErrorCodes.ValidationFailed, validation.IsFailure ? validation.ErrorMessage! : string.Join("; ", validation.Value.Errors));
        var imported = await _importer.ImportSnapshotToStagingAsync(new SnapshotImportRequest(manifestPath, stagingRoot), ct); if (imported.IsFailure || imported.Value.StagingDatabasePath is null) return Result<SnapshotBranchInspectionInfo>.Failure(AppErrorCodes.ValidationFailed, imported.IsFailure ? imported.ErrorMessage! : string.Join("; ", imported.Value.Warnings));
        var m = validation.Value.Manifest; var mismatch = !string.Equals(m.LibraryId, local.Value.LibraryId.ToString(), StringComparison.OrdinalIgnoreCase);
        return Result<SnapshotBranchInspectionInfo>.Success(new(Guid.NewGuid().ToString("D"), LibraryId.Parse(m.LibraryId), m.SnapshotId, m.ParentSnapshotId, null, m.DeviceId, m.CreatedAt, manifestPath, imported.Value.StagingDatabasePath, !mismatch, mismatch, mismatch ? new[] { "Branch library differs from active runtime library; import is blocked." } : imported.Value.Warnings));
    }

    public async Task<Result<IReadOnlyList<BranchItemSummary>>> ListBranchItemsAsync(SnapshotBranchInspectionInfo b, CancellationToken ct = default)
    {
        try { await using var c = OpenRead(b.StagingDatabasePath); var rows = await c.QueryAsync<ItemRow>("select i.item_id ItemId,i.title Title,i.item_type ItemType,i.date Date,i.creators_json CreatorsJson,(select count(*) from document_instances d where d.item_id=i.item_id) DocumentCount,(select count(*) from document_instances d join layout_revisions r on r.document_instance_id=d.document_instance_id and r.is_current=1 join layout_nodes n on n.revision_id=r.layout_revision_id where d.item_id=i.item_id and length(trim(coalesce(n.own_text,'')))>0) OcrCount,(select count(*) from search_units s join document_instances d on d.document_instance_id=s.document_instance_id where d.item_id=i.item_id) SearchCount,(select count(*) from evidence_ref_records e join document_instances d on d.document_instance_id=e.document_instance_id where d.item_id=i.item_id) EvidenceCount from items i order by i.title;"); return Result<IReadOnlyList<BranchItemSummary>>.Success(rows.Select(x=>new BranchItemSummary(ItemId.Parse(x.ItemId),x.Title,x.ItemType,x.Date,x.CreatorsJson,x.DocumentCount,x.OcrCount>0,x.SearchCount>0,x.EvidenceCount>0,null)).ToArray()); } catch(Exception ex){return Result<IReadOnlyList<BranchItemSummary>>.Failure(AppErrorCodes.DatabaseError,ex.Message);}
    }
    public async Task<Result<IReadOnlyList<BranchDocumentInstanceSummary>>> ListBranchDocumentInstancesAsync(SnapshotBranchInspectionInfo b, ItemId? itemId = null, CancellationToken ct = default)
    {
        try { await using var c=OpenRead(b.StagingDatabasePath); var rows=await c.QueryAsync<DocRow>("select d.document_instance_id DocumentId,d.item_id ItemId,d.title Title,d.instance_type InstanceType,d.is_primary IsPrimary,coalesce(f.status,'unknown') SourceStatus,(select count(*) from pages p where p.document_instance_id=d.document_instance_id) Pages,(select count(*) from layout_revisions r where r.document_instance_id=d.document_instance_id) Revisions,(select count(*) from search_units s where s.document_instance_id=d.document_instance_id) Units,(select count(*) from evidence_ref_records e where e.document_instance_id=d.document_instance_id) Evidence from document_instances d left join file_assets f on f.file_asset_id=d.file_asset_id where (@ItemId is null or d.item_id=@ItemId) order by d.created_at;",new{ItemId=itemId?.ToString()}); return Result<IReadOnlyList<BranchDocumentInstanceSummary>>.Success(rows.Select(x=>new BranchDocumentInstanceSummary(DocumentInstanceId.Parse(x.DocumentId),ItemId.Parse(x.ItemId),x.Title,x.InstanceType,x.IsPrimary!=0,x.Pages,x.Revisions,x.Units,x.Evidence,x.SourceStatus,null)).ToArray()); }catch(Exception ex){return Result<IReadOnlyList<BranchDocumentInstanceSummary>>.Failure(AppErrorCodes.DatabaseError,ex.Message);}
    }
    public async Task<Result<BranchImportPlan>> BuildImportPlanAsync(SnapshotBranchInspectionInfo b,IReadOnlyList<ItemId> items,IReadOnlyList<DocumentInstanceId> docs,CancellationToken ct=default)
    {
        var current=await _library.GetCurrentLibraryAsync(ct); if(current.IsFailure)return Result<BranchImportPlan>.Failure(current.ErrorCode!,current.ErrorMessage!); if(!b.IsLibraryMatch)return Result<BranchImportPlan>.Failure(AppErrorCodes.LibraryMismatch,"Branch library does not match active runtime library.");
        try { await using var s=OpenRead(b.StagingDatabasePath); var selectedItems=new HashSet<string>(items.Select(x=>x.ToString())); var selectedDocs=new HashSet<string>(docs.Select(x=>x.ToString())); foreach(var id in docs) { var owner=await s.ExecuteScalarAsync<string?>("select item_id from document_instances where document_instance_id=@Id",new{Id=id.ToString()}); if(owner is not null)selectedItems.Add(owner); } foreach(var item in selectedItems.ToArray()) foreach(var doc in await s.QueryAsync<string>("select document_instance_id from document_instances where item_id=@Id and is_primary=1",new{Id=item})) selectedDocs.Add(doc);
            var conflicts=new List<BranchImportConflict>(); await using var t=_target.CreateConnection(); await t.OpenAsync(ct); foreach(var item in selectedItems){var source=await s.QuerySingleOrDefaultAsync<ItemContent>("select item_id Id,title Title,item_type ItemType from items where item_id=@Id",new{Id=item});var target=await t.QuerySingleOrDefaultAsync<ItemContent>("select item_id Id,title Title,item_type ItemType from items where item_id=@Id",new{Id=item});if(source is not null&&target is not null&&(source.Title!=target.Title||source.ItemType!=target.ItemType))conflicts.Add(new("item",item,item,"same_id_different_content","manual_pick"));} var docList=selectedDocs.ToArray(); foreach(var doc in docList){var branchPrimary=await s.ExecuteScalarAsync<int>("select is_primary from document_instances where document_instance_id=@Id",new{Id=doc});var owner=await s.ExecuteScalarAsync<string>("select item_id from document_instances where document_instance_id=@Id",new{Id=doc});if(branchPrimary!=0&&await t.ExecuteScalarAsync<int>("select count(*) from document_instances where item_id=@Item and is_primary=1",new{Item=owner})>0)conflicts.Add(new("document_instance",doc,null,"primary_document_conflict","manual_pick"));} var ids=selectedItems.Select(ItemId.Parse).ToArray(); var count=docList.Length==0?0:await s.ExecuteScalarAsync<int>($"select count(*) from pages where document_instance_id in ({string.Join(',',docList.Select((_,i)=>"@d"+i))})",docList.Select((x,i)=>new KeyValuePair<string,object>("d"+i,x)).ToDictionary()); var revisions=docList.Length==0?0:await s.ExecuteScalarAsync<int>("select count(*) from layout_revisions where document_instance_id in @Docs",new{Docs=docList}); var units=docList.Length==0?0:await s.ExecuteScalarAsync<int>("select count(*) from search_units where document_instance_id in @Docs",new{Docs=docList}); var evidence=docList.Length==0?0:await s.ExecuteScalarAsync<int>("select count(*) from evidence_ref_records where document_instance_id in @Docs",new{Docs=docList}); return Result<BranchImportPlan>.Success(new(Guid.NewGuid().ToString("D"),b,current.Value.LibraryId,ids,docList.Select(DocumentInstanceId.Parse).ToArray(),count,revisions,units,evidence,docList.Length,conflicts.Append(new BranchImportConflict("credential","*",null,"credential_not_imported","reenter_credential")).ToArray(),new[]{"Original files, local FTS cache, render cache, and provider secrets are not imported. Rebuild FTS after import."},true)); }catch(Exception ex){return Result<BranchImportPlan>.Failure(AppErrorCodes.DatabaseError,ex.Message);}
    }
    public async Task<Result<BranchImportResult>> ApplyImportPlanAsync(BranchImportPlan p,bool confirmed,CancellationToken ct=default)
    { if(!confirmed)return Result<BranchImportResult>.Failure("requires_confirmation","Selective import requires explicit user confirmation."); if(p.Conflicts.Any(x=>x.RecommendedAction=="manual_pick"))return Result<BranchImportResult>.Failure("conflict_unresolved","Import plan has unresolved conflicts."); try{await using var c=_target.CreateConnection();await c.OpenAsync(ct);await c.ExecuteAsync("attach database @Path as branch;",new{Path=p.SourceBranch.StagingDatabasePath});await using var tx=await c.BeginTransactionAsync(ct);var items=p.ItemsToImport.Select(x=>x.ToString()).ToArray();var docs=p.DocumentInstancesToImport.Select(x=>x.ToString()).ToArray();if(items.Length>0){await c.ExecuteAsync("insert into items select * from branch.items where item_id in @Ids; insert into item_identifiers select * from branch.item_identifiers where item_id in @Ids;",new{Ids=items},tx);}if(docs.Length>0){await c.ExecuteAsync("insert into file_assets select f.* from branch.file_assets f join branch.document_instances d on d.file_asset_id=f.file_asset_id where d.document_instance_id in @Docs and not exists(select 1 from file_assets x where x.file_asset_id=f.file_asset_id); insert into document_instances select * from branch.document_instances where document_instance_id in @Docs; insert into pages select * from branch.pages where document_instance_id in @Docs; insert into layout_revisions select * from branch.layout_revisions where document_instance_id in @Docs; insert into layout_nodes select * from branch.layout_nodes where document_instance_id in @Docs; insert into search_units select * from branch.search_units where document_instance_id in @Docs; insert into evidence_ref_records select * from branch.evidence_ref_records where document_instance_id in @Docs;",new{Docs=docs},tx);foreach(var d in docs)await c.ExecuteAsync("insert into search_index_status(scope_type,scope_id,status,pending_document_count,pending_unit_count,progress_percent,affected_scopes_summary,reason,updated_at) values('document_instance',@Id,'stale',1,0,null,'Selective branch import requires FTS rebuild',null,@Now) on conflict(scope_type,scope_id) do update set status='stale',affected_scopes_summary=excluded.affected_scopes_summary,updated_at=excluded.updated_at;",new{Id=d,Now=DateTimeOffset.UtcNow.ToString("O")},tx);}await tx.CommitAsync(ct);return Result<BranchImportResult>.Success(new(true,items.Length,docs.Length,p.PagesToImport,p.SearchUnitsToImport,p.EvidenceRefsToImport,Array.Empty<BranchImportConflict>(),p.Warnings,p.DocumentInstancesToImport));}catch(Exception ex){return Result<BranchImportResult>.Failure(AppErrorCodes.DatabaseError,ex.Message);} }
    public Task<Result> DiscardBranchAsync(SnapshotBranchInspectionInfo b,CancellationToken ct=default){try{if(File.Exists(b.StagingDatabasePath))File.Delete(b.StagingDatabasePath);return Task.FromResult(Result.Success());}catch(Exception ex){return Task.FromResult(Result.Failure(AppErrorCodes.DatabaseError,ex.Message));}}
    public Task<Result<string>> KeepBranchAsSeparateLibraryCopyAsync(SnapshotBranchInspectionInfo b,string destination,CancellationToken ct=default){try{Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(destination))!);File.Copy(b.StagingDatabasePath,destination,true);return Task.FromResult(Result<string>.Success(destination));}catch(Exception ex){return Task.FromResult(Result<string>.Failure(AppErrorCodes.DatabaseError,ex.Message));}}
    private static Microsoft.Data.Sqlite.SqliteConnection OpenRead(string path){var c=new Microsoft.Data.Sqlite.SqliteConnection(new Microsoft.Data.Sqlite.SqliteConnectionStringBuilder{DataSource=path,Mode=Microsoft.Data.Sqlite.SqliteOpenMode.ReadOnly,ForeignKeys=true}.ToString());c.Open();return c;} private sealed class ItemRow{public string ItemId{get;set;}="";public string Title{get;set;}="";public string ItemType{get;set;}="";public string? Date{get;set;}public string CreatorsJson{get;set;}="";public int DocumentCount{get;set;}public int OcrCount{get;set;}public int SearchCount{get;set;}public int EvidenceCount{get;set;}}private sealed class DocRow{public string DocumentId{get;set;}="";public string ItemId{get;set;}="";public string? Title{get;set;}public string InstanceType{get;set;}="";public int IsPrimary{get;set;}public string SourceStatus{get;set;}="";public int Pages{get;set;}public int Revisions{get;set;}public int Units{get;set;}public int Evidence{get;set;}}private sealed class ItemContent{public string Id{get;set;}="";public string Title{get;set;}="";public string ItemType{get;set;}="";}
}
