using Dapper;
using Patchouli.Core.Credentials;
using Patchouli.Core.Ids;
using Patchouli.Core.Library;
using Patchouli.Core.Results;
using Patchouli.Core.Time;
using Patchouli.Infrastructure.Database;

namespace Patchouli.Infrastructure.Credentials;

public sealed class CredentialStore : ICredentialStore
{
    private readonly SqliteConnectionFactory _factory; private readonly ILibraryIdentityService _library; private readonly IClock _clock;
    public CredentialStore(SqliteConnectionFactory factory, ILibraryIdentityService library, IClock clock) { _factory = factory; _library = library; _clock = clock; }
    public async Task<Result<ProviderCredentialMetadata>> SaveCredentialAsync(string providerId, string displayName, string secretValue, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(providerId)||string.IsNullOrWhiteSpace(displayName)||string.IsNullOrWhiteSpace(secretValue)) return Result<ProviderCredentialMetadata>.Failure(AppErrorCodes.ValidationFailed,"Provider, display name, and secret are required.");
        var lib=await _library.GetCurrentLibraryAsync(cancellationToken); if(lib.IsFailure) return Result<ProviderCredentialMetadata>.Failure(lib.ErrorCode!,lib.ErrorMessage!);
        try { var now=_clock.UtcNow.ToUniversalTime(); var id=CredentialId.New(); await using var c=_factory.CreateConnection(); await c.OpenAsync(cancellationToken); await c.ExecuteAsync("insert into provider_credentials (credential_id,library_id,provider_id,display_name,secret_value,status,created_at,updated_at) values (@Id,@Lib,@Provider,@Name,@Secret,'active',@Now,@Now);",new {Id=id.ToString(),Lib=lib.Value.LibraryId.ToString(),Provider=providerId.Trim(),Name=displayName.Trim(),Secret=secretValue,Now=now.ToString("O")}); return Result<ProviderCredentialMetadata>.Success(new(id,lib.Value.LibraryId,providerId.Trim(),displayName.Trim(),ProviderCredentialStatus.Active,now,now)); }
        catch(Exception ex){return Result<ProviderCredentialMetadata>.Failure(AppErrorCodes.DatabaseError,ex.Message);}
    }
    public async Task<Result<ProviderCredentialMetadata>> GetCredentialMetadataAsync(CredentialId credentialId,CancellationToken cancellationToken=default){var rows=await ListRowsAsync(cancellationToken); var r=rows.FirstOrDefault(x=>x.CredentialId==credentialId); return r is null?Result<ProviderCredentialMetadata>.Failure(AppErrorCodes.NotFound,"Credential was not found."):Result<ProviderCredentialMetadata>.Success(r);}
    public async Task<Result<string>> GetSecretForInternalUseAsync(CredentialId credentialId,CancellationToken cancellationToken=default){try{await using var c=_factory.CreateConnection();await c.OpenAsync(cancellationToken);var row=await c.QuerySingleOrDefaultAsync<(string Secret,string Status)>("select secret_value as Secret,status as Status from provider_credentials where credential_id=@Id;",new{Id=credentialId.ToString()});if(string.IsNullOrEmpty(row.Secret))return Result<string>.Failure(AppErrorCodes.NotFound,"Credential was not found.");if(row.Status!=ProviderCredentialStatus.Active)return Result<string>.Failure(AppErrorCodes.InvalidState,"Credential is not active.");return Result<string>.Success(row.Secret);}catch(Exception ex){return Result<string>.Failure(AppErrorCodes.DatabaseError,ex.Message);}}
    public async Task<Result<ProviderCredentialBinding>> BindCredentialToPresetAsync(CredentialId credentialId,OcrPresetId presetId,CancellationToken cancellationToken=default){var meta=await GetCredentialMetadataAsync(credentialId,cancellationToken);if(meta.IsFailure)return Result<ProviderCredentialBinding>.Failure(meta.ErrorCode!,meta.ErrorMessage!);if(meta.Value.Status!=ProviderCredentialStatus.Active)return Result<ProviderCredentialBinding>.Failure(AppErrorCodes.InvalidState,"Credential is not active.");try{await using var c=_factory.CreateConnection();await c.OpenAsync(cancellationToken);var provider=await c.ExecuteScalarAsync<string?>("select provider_id from provider_credentials where credential_id=@Id;",new{Id=credentialId.ToString()});var preset=await c.ExecuteScalarAsync<int>("select count(1) from ocr_presets where preset_id=@Id;",new{Id=presetId.ToString()});if(preset==0)return Result<ProviderCredentialBinding>.Failure(AppErrorCodes.NotFound,"OCR preset was not found.");var now=_clock.UtcNow.ToUniversalTime();var b=new ProviderCredentialBinding(Guid.NewGuid().ToString("D"),credentialId,presetId,provider!,ProviderCredentialBindingStatus.Active,now,now);await c.ExecuteAsync("insert into provider_credential_bindings (binding_id,credential_id,preset_id,provider_id,status,created_at,updated_at) values (@Id,@Credential,@Preset,@Provider,@Status,@Now,@Now);",new{Id=b.BindingId,Credential=credentialId.ToString(),Preset=presetId.ToString(),Provider=b.ProviderId,Status=b.Status,Now=now.ToString("O")});return Result<ProviderCredentialBinding>.Success(b);}catch(Exception ex){return Result<ProviderCredentialBinding>.Failure(AppErrorCodes.DatabaseError,ex.Message);}}
    public Task<Result> RevokeCredentialAsync(CredentialId credentialId,CancellationToken cancellationToken=default)=>SetStatusAsync(credentialId,ProviderCredentialStatus.Revoked,ProviderCredentialBindingStatus.Revoked,"[revoked]",cancellationToken);
    public Task<Result> EmergencyPurgeCredentialAsync(CredentialId credentialId,CancellationToken cancellationToken=default)=>SetStatusAsync(credentialId,ProviderCredentialStatus.Purged,ProviderCredentialBindingStatus.CredentialMissing,"[purged]",cancellationToken);
    public async Task<Result<IReadOnlyList<ProviderCredentialMetadata>>> ListCredentialsAsync(CancellationToken cancellationToken=default){try{return Result<IReadOnlyList<ProviderCredentialMetadata>>.Success(await ListRowsAsync(cancellationToken));}catch(Exception ex){return Result<IReadOnlyList<ProviderCredentialMetadata>>.Failure(AppErrorCodes.DatabaseError,ex.Message);}}
    private async Task<Result> SetStatusAsync(CredentialId id,string status,string bindingStatus,string secret,CancellationToken ct){try{await using var c=_factory.CreateConnection();await c.OpenAsync(ct);var n=await c.ExecuteAsync("update provider_credentials set status=@Status,secret_value=@Secret,updated_at=@Now where credential_id=@Id; update provider_credential_bindings set status=@Binding,updated_at=@Now where credential_id=@Id;",new{Id=id.ToString(),Status=status,Secret=secret,Binding=bindingStatus,Now=_clock.UtcNow.ToUniversalTime().ToString("O")});return n==0?Result.Failure(AppErrorCodes.NotFound,"Credential was not found."):Result.Success();}catch(Exception ex){return Result.Failure(AppErrorCodes.DatabaseError,ex.Message);}}
    private async Task<IReadOnlyList<ProviderCredentialMetadata>> ListRowsAsync(CancellationToken ct){await using var c=_factory.CreateConnection();await c.OpenAsync(ct);var rows=await c.QueryAsync<Row>("select credential_id as CredentialId,library_id as LibraryId,provider_id as ProviderId,display_name as DisplayName,status as Status,created_at as CreatedAt,updated_at as UpdatedAt from provider_credentials order by created_at;");return rows.Select(r=>new ProviderCredentialMetadata(CredentialId.Parse(r.CredentialId),LibraryId.Parse(r.LibraryId),r.ProviderId,r.DisplayName,r.Status,DateTimeOffset.Parse(r.CreatedAt),DateTimeOffset.Parse(r.UpdatedAt))).ToArray();}
    private sealed class Row{public string CredentialId{get;set;}="";public string LibraryId{get;set;}="";public string ProviderId{get;set;}="";public string DisplayName{get;set;}="";public string Status{get;set;}="";public string CreatedAt{get;set;}="";public string UpdatedAt{get;set;}="";}
}
