using FluentAssertions;
using Patchouli.McpServer;
using Patchouli.Infrastructure.Database;
using Patchouli.Infrastructure.Migrations;
using Dapper;

namespace Patchouli.Tests;
public sealed class McpServerTransportTests
{
    [Fact] public void Sanitizer_redacts_paths_file_urls_cache_and_secrets(){var value="file:///Users/test/cache/render.png api_key=FAKE_SECRET model_path=/bin/tool";var safe=McpOutputSanitizer.Sanitize(value);safe.Should().NotContain("/Users").And.NotContain("FAKE_SECRET").And.NotContain("/bin/tool");}
    [Fact] public void Sanitizer_identifies_safe_text(){McpOutputSanitizer.IsSafe("ordinary scholarly text").Should().BeTrue();}
    [Fact] public void Sanitizer_preserves_json_escaped_chinese_text(){var value="{\\\"text\\\":\\\"\\u534e\\u5317\\u89e3\\u653e\\u533a\\\"}";McpOutputSanitizer.Sanitize(value).Should().Be(value);}
    [Fact] public async Task Initialize_reports_current_build_version(){var h=new McpProtocolHandler(new FakeApi(),new SqliteConnectionFactory(Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".sqlite")));var response=await h.HandleAsync("{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\"}");response.Should().Contain(Patchouli.Core.BuildInfo.Version);}
    [Fact] public void Mcp_interface_has_exactly_six_read_tools(){typeof(Patchouli.Mcp.IMcpReadApi).GetMethods().Select(x=>x.Name).Should().HaveCount(6).And.OnlyContain(x=>x.StartsWith("Get")||x=="SearchLibraryAsync");}
    [Fact] public void Mcp_interface_has_no_transport_write_or_branch_methods(){typeof(Patchouli.Mcp.IMcpReadApi).GetMethods().Select(x=>x.Name).Should().NotContain(x=>x.Contains("Import",StringComparison.OrdinalIgnoreCase)||x.Contains("Branch",StringComparison.OrdinalIgnoreCase)||x.Contains("Queue",StringComparison.OrdinalIgnoreCase)||x.Contains("Ocr",StringComparison.OrdinalIgnoreCase));}
    [Theory]
    [InlineData("/Users/a86186/secret/runtime.sqlite")]
    [InlineData("C:\\Users\\test\\secret.db")]
    [InlineData("file:///Users/a86186/test.pdf")]
    [InlineData("/tmp/app-cache/page-renders/render.png")]
    [InlineData("cache/page-renders/render.png")]
    [InlineData("FAKE_PROVIDER_SECRET_123")]
    [InlineData("sk-test-1234567890")]
    [InlineData("/usr/local/bin/ocr-engine")]
    [InlineData("/models/ocr/model.onnx")]
    [InlineData("/tmp/snapshots/manifest.json")]
    public void Response_sanitizer_redacts_sensitive_patterns(string value){McpOutputSanitizer.Sanitize(value).Should().NotContain(value);}
    [Fact] public async Task Protocol_initialize_tools_list_unknown_and_invalid_args_are_sanitized(){var h=new McpProtocolHandler(new FakeApi(),new SqliteConnectionFactory(Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".sqlite")));var init=await h.HandleAsync("{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\"}");init.Should().Contain("Patchouli").And.Contain("tools");var list=await h.HandleAsync("{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/list\"}");list.Should().Contain("search_library").And.Contain("get_page_blocks");var unknown=await h.HandleAsync("{\"id\":3,\"method\":\"tools/call\",\"params\":{\"name\":\"write_secret\",\"arguments\":{}}}");unknown.Should().Contain("unknown_tool");var invalid=await h.HandleAsync("{\"id\":4,\"method\":\"tools/call\",\"params\":{\"name\":\"search_library\",\"arguments\":{}}}");invalid.Should().Contain("error");}
    [Fact] public async Task Tools_call_delegates_search_item_document_and_context_arguments(){var db=TemporarySqliteDatabase.Create();try{var api=new FakeApi();var h=new McpProtocolHandler(api,db.ConnectionFactory);await h.HandleAsync("{\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"search_library\",\"arguments\":{\"query\":\"needle\",\"limit\":7,\"cursor\":\"c\",\"profile_alias\":\"p\",\"include_evidence_refs\":false}}}");api.Search!.Query.Should().Be("needle");api.Search.PageSize.Should().Be(7);api.Search.Cursor.Should().Be("c");api.Search.IncludeEvidenceRefs.Should().BeFalse();var item=Patchouli.Core.Ids.ItemId.New();await h.HandleAsync($"{{\"id\":2,\"method\":\"tools/call\",\"params\":{{\"name\":\"get_item_metadata\",\"arguments\":{{\"item_id\":\"{item}\"}}}}}}");api.Item.Should().Be(item);var doc=Patchouli.Core.Ids.DocumentInstanceId.New();await h.HandleAsync($"{{\"id\":3,\"method\":\"tools/call\",\"params\":{{\"name\":\"get_document_status\",\"arguments\":{{\"document_instance_id\":\"{doc}\"}}}}}}");api.Document.Should().Be(doc);var unit=Patchouli.Core.Ids.SearchUnitId.New();await h.HandleAsync($"{{\"id\":4,\"method\":\"tools/call\",\"params\":{{\"name\":\"get_search_result_context\",\"arguments\":{{\"search_unit_id\":\"{unit}\"}}}}}}");api.Context!.SearchUnitId.Should().Be(unit);}finally{await db.DisposeAsync();}}
    [Fact] public async Task Tools_call_delegates_page_text_and_blocks_bbox_flag(){await using var db=TemporarySqliteDatabase.Create();await new MigrationRunner(db.ConnectionFactory,TestPaths.MigrationsDirectory).RunAsync();var doc=Patchouli.Core.Ids.DocumentInstanceId.New();var page=Patchouli.Core.Ids.PageId.New();await using(var c=db.ConnectionFactory.CreateConnection()){await c.OpenAsync();await c.ExecuteAsync("pragma foreign_keys=off;insert into pages(page_id,document_instance_id,page_index,rotation,coordinate_basis,renderer_basis_version,created_at,updated_at) values(@P,@D,3,0,'normalized_page','t','2026-01-01T00:00:00Z','2026-01-01T00:00:00Z');",new{P=page.ToString(),D=doc.ToString()});}var api=new FakeApi();var h=new McpProtocolHandler(api,db.ConnectionFactory);await h.HandleAsync($"{{\"id\":1,\"method\":\"tools/call\",\"params\":{{\"name\":\"get_page_text\",\"arguments\":{{\"document_instance_id\":\"{doc}\",\"page_number\":3,\"mode\":\"pinned\",\"evidence_ref\":\"evref:v1:x\"}}}}}}");api.Text!.PageId.Should().Be(page);api.Text.ReadMode.Should().Be("pinned");await h.HandleAsync($"{{\"id\":2,\"method\":\"tools/call\",\"params\":{{\"name\":\"get_page_blocks\",\"arguments\":{{\"document_instance_id\":\"{doc}\",\"page_number\":3,\"include_bbox\":true}}}}}}");api.Blocks!.PageId.Should().Be(page);api.Blocks.IncludeBbox.Should().BeTrue();}
    [Fact] public void Agent_prd_documents_stdio_read_only_mcp_boundaries(){var r=File.ReadAllText(TestPaths.FromRepositoryRoot(".agent","PRD.md"));r.Should().Contain("First version MCP is read-only and text-only").And.Contain("MCP never triggers OCR or index rebuild").And.Contain("provider secrets").And.Contain("cache images");}

    private sealed class FakeApi : Patchouli.Mcp.IMcpReadApi
    {
        public Patchouli.Mcp.McpSearchLibraryRequest? Search;public Patchouli.Core.Ids.ItemId? Item;public Patchouli.Core.Ids.DocumentInstanceId? Document;public Patchouli.Mcp.McpPageTextRequest? Text;public Patchouli.Mcp.McpPageBlocksRequest? Blocks;public Patchouli.Mcp.McpSearchContextRequest? Context;
        public Task<Patchouli.Core.Results.Result<Patchouli.Mcp.McpSearchLibraryResponse>> SearchLibraryAsync(Patchouli.Mcp.McpSearchLibraryRequest r,CancellationToken c=default){Search=r;return Task.FromResult(Patchouli.Core.Results.Result<Patchouli.Mcp.McpSearchLibraryResponse>.Failure("fake","/Users/test/FAKE_PROVIDER_SECRET_123"));}
        public Task<Patchouli.Core.Results.Result<Patchouli.Mcp.McpItemMetadataResponse>> GetItemMetadataAsync(Patchouli.Core.Ids.ItemId i,CancellationToken c=default){Item=i;return Task.FromResult(Patchouli.Core.Results.Result<Patchouli.Mcp.McpItemMetadataResponse>.Failure("fake","x"));}
        public Task<Patchouli.Core.Results.Result<Patchouli.Mcp.McpDocumentStatusResponse>> GetDocumentStatusAsync(Patchouli.Core.Ids.DocumentInstanceId i,CancellationToken c=default){Document=i;return Task.FromResult(Patchouli.Core.Results.Result<Patchouli.Mcp.McpDocumentStatusResponse>.Failure("fake","x"));}
        public Task<Patchouli.Core.Results.Result<Patchouli.Mcp.McpPageTextResponse>> GetPageTextAsync(Patchouli.Mcp.McpPageTextRequest r,CancellationToken c=default){Text=r;return Task.FromResult(Patchouli.Core.Results.Result<Patchouli.Mcp.McpPageTextResponse>.Failure("fake","x"));}
        public Task<Patchouli.Core.Results.Result<Patchouli.Mcp.McpPageBlocksResponse>> GetPageBlocksAsync(Patchouli.Mcp.McpPageBlocksRequest r,CancellationToken c=default){Blocks=r;return Task.FromResult(Patchouli.Core.Results.Result<Patchouli.Mcp.McpPageBlocksResponse>.Failure("fake","x"));}
        public Task<Patchouli.Core.Results.Result<Patchouli.Mcp.McpSearchContextResponse>> GetSearchResultContextAsync(Patchouli.Mcp.McpSearchContextRequest r,CancellationToken c=default){Context=r;return Task.FromResult(Patchouli.Core.Results.Result<Patchouli.Mcp.McpSearchContextResponse>.Failure("fake","x"));}
    }
}
