using Dapper;
using FluentAssertions;
using Patchouli.Core.Bibliography;
using Patchouli.Core.Documents;
using Patchouli.Core.Ids;
using Patchouli.Core.Layout;
using Patchouli.Core.Results;
using Patchouli.Infrastructure.Bibliography;
using Patchouli.Infrastructure.Documents;
using Patchouli.Infrastructure.Layout;
using Patchouli.Infrastructure.LibraryIdentity;
using Patchouli.Infrastructure.Migrations;
using Patchouli.Infrastructure.Ocr;
using Patchouli.Ocr;
using Microsoft.Data.Sqlite;

namespace Patchouli.Tests;

public sealed class OcrLifecycleTests
{
    [Fact] public async Task CreatePreset_creates_current_version() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); p.Value.CurrentVersionId.Should().NotBeNull(); }
    [Fact] public async Task CreatePreset_rejects_blank_name() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.PresetService.CreatePresetAsync(" ", null, OcrEngineIds.Mock, OcrModelIds.MockBasic, null, "{}", false); p.ErrorCode.Should().Be(AppErrorCodes.ValidationFailed); }
    [Fact] public async Task CreatePresetVersion_updates_current_version() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var old = p.Value.CurrentVersionId; var v = await c.PresetService.CreatePresetVersionAsync(p.Value.PresetId, OcrEngineIds.Mock, OcrModelIds.MockBasic, null, "{\"failPages\":[1]}", true); var updated = await c.PresetService.GetPresetAsync(p.Value.PresetId); updated.Value.CurrentVersionId.Should().Be(v.Value.PresetVersionId); updated.Value.CurrentVersionId.Should().NotBe(old); }
    [Fact] public async Task ArchivePreset_blocks_future_runs() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); await c.PresetService.ArchivePresetAsync(p.Value.PresetId); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); r.ErrorCode.Should().Be(AppErrorCodes.InvalidState); }
    [Fact] public async Task RunPresetOnPages_creates_run_and_page_results() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, c.Pages.Select(x => x.PageId).ToArray()); var results = await c.Coordinator.ListPageResultsAsync(r.Value.OcrRunId); r.Value.State.Should().Be(OcrRunState.Completed); results.Value.Should().HaveCount(3); }
    [Fact] public async Task Successful_mock_run_creates_staging_revision() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); r.Value.OutputRevisionId.Should().NotBeNull(); (await c.CountNodesAsync(r.Value.OutputRevisionId!.Value)).Should().Be(1); }
    [Fact] public async Task apply_on_success_false_does_not_set_current_revision() { await using var c = await OcrTestContext.CreateAsync(); var current = await c.LayoutTreeService.GetCurrentRevisionAsync(c.DocumentInstanceId); var p = await c.CreatePresetAsync(apply: false); await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); var after = await c.LayoutTreeService.GetCurrentRevisionAsync(c.DocumentInstanceId); after.Value.LayoutRevisionId.Should().Be(current.Value.LayoutRevisionId); }
    [Fact] public async Task apply_on_success_true_sets_staging_revision_as_current() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(apply: true); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); var current = await c.LayoutTreeService.GetCurrentRevisionAsync(c.DocumentInstanceId); current.Value.LayoutRevisionId.Should().Be(r.Value.OutputRevisionId); }
    [Fact] public async Task Partial_failure_results_in_completed_with_errors() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(parameters: "{\"failPages\":[1]}"); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, c.Pages.Select(x => x.PageId).ToArray()); r.Value.State.Should().Be(OcrRunState.CompletedWithErrors); }
    [Fact] public async Task All_pages_failed_results_in_failed() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(parameters: "{\"failPages\":[0,1,2]}"); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, c.Pages.Select(x => x.PageId).ToArray()); r.Value.State.Should().Be(OcrRunState.Failed); }
    [Fact] public async Task Bbox_coordinate_failure_rejects_whole_page_and_writes_no_node() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(parameters: "{\"bboxFailurePages\":[2]}"); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[2].PageId]); var results = await c.Coordinator.ListPageResultsAsync(r.Value.OcrRunId); results.Value.Single().ErrorCode.Should().Be(OcrFailureCode.BBoxCoordinateTransformFailed); (await c.CountNodesAsync(r.Value.OutputRevisionId!.Value)).Should().Be(0); }
    [Fact] public async Task Run_rejects_page_from_other_document_instance() { await using var c = await OcrTestContext.CreateAsync(); var otherItem = await c.ItemService.CreateItemAsync("book", "Other"); var otherDoc = await c.DocumentInstanceService.AttachDocumentInstanceAsync(otherItem.Value.ItemId, null, DocumentInstanceType.PrimaryScan); var otherPage = await c.PageService.CreatePageAsync(otherDoc.Value.DocumentInstanceId, 0, null, 100, 200, 0, CoordinateBasis.NormalizedPage, 100, 200, "renderer-v1", null); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [otherPage.Value.PageId]); r.ErrorCode.Should().Be(AppErrorCodes.ValidationFailed); }
    [Fact] public async Task Run_rejects_missing_page() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [PageId.New()]); r.ErrorCode.Should().Be(AppErrorCodes.NotFound); }
    [Fact] public async Task Run_rejects_archived_preset() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); await c.PresetService.ArchivePresetAsync(p.Value.PresetId); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); r.ErrorCode.Should().Be(AppErrorCodes.InvalidState); }
    [Fact] public async Task Run_rejects_empty_page_list() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, []); r.ErrorCode.Should().Be(AppErrorCodes.ValidationFailed); }
    [Fact] public async Task Cancel_pending_or_running_run_marks_cancelled_and_does_not_change_current() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var current = await c.LayoutTreeService.GetCurrentRevisionAsync(c.DocumentInstanceId); var pending = await c.Coordinator.CreatePendingRunForTestAsync(c.DocumentInstanceId, p.Value.PresetId); var cancel = await c.Coordinator.CancelRunAsync(pending.Value.OcrRunId); var after = await c.Coordinator.GetRunAsync(pending.Value.OcrRunId); var currentAfter = await c.LayoutTreeService.GetCurrentRevisionAsync(c.DocumentInstanceId); cancel.IsSuccess.Should().BeTrue(); after.Value.State.Should().Be(OcrRunState.Cancelled); currentAfter.Value.LayoutRevisionId.Should().Be(current.Value.LayoutRevisionId); }
    [Fact] public async Task AdoptCandidateRun_sets_current_revision() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); var adoption = await c.Coordinator.AdoptCandidateRunAsync(r.Value.OcrRunId); var current = await c.LayoutTreeService.GetCurrentRevisionAsync(c.DocumentInstanceId); current.Value.LayoutRevisionId.Should().Be(adoption.Value.AdoptedRevisionId); }
    [Fact] public async Task AdoptCandidateRun_selected_pages_only_copies_selected_pages() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, c.Pages.Select(x => x.PageId).ToArray()); var adoption = await c.Coordinator.AdoptCandidateRunAsync(r.Value.OcrRunId, [c.Pages[1].PageId]); (await c.PageIdsWithNodesAsync(adoption.Value.AdoptedRevisionId)).Should().Equal(c.Pages[1].PageId); }
    [Fact] public async Task AdoptCandidateRun_rejects_failed_pages() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(parameters: "{\"failPages\":[1]}"); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, c.Pages.Select(x => x.PageId).ToArray()); var adoption = await c.Coordinator.AdoptCandidateRunAsync(r.Value.OcrRunId, [c.Pages[1].PageId]); adoption.ErrorCode.Should().Be(AppErrorCodes.ValidationFailed); }
    [Fact] public async Task AdoptCandidateRun_records_candidate_adoption() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); await c.Coordinator.AdoptCandidateRunAsync(r.Value.OcrRunId); (await c.CountAdoptionsAsync(r.Value.OcrRunId)).Should().Be(1); }
    [Fact] public async Task AdoptCandidateRun_rejects_failed_run() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(parameters: "{\"failPages\":[0]}"); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); var adoption = await c.Coordinator.AdoptCandidateRunAsync(r.Value.OcrRunId); adoption.ErrorCode.Should().Be(AppErrorCodes.InvalidState); }
    [Fact] public async Task Adoption_keeps_only_one_current_revision() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); await c.Coordinator.AdoptCandidateRunAsync(r.Value.OcrRunId); (await c.CountCurrentRevisionsAsync()).Should().Be(1); }
    [Fact] public async Task Adoption_is_serialized_per_document_instance() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r1 = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); var r2 = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[1].PageId]); await Task.WhenAll(c.Coordinator.AdoptCandidateRunAsync(r1.Value.OcrRunId), c.Coordinator.AdoptCandidateRunAsync(r2.Value.OcrRunId)); (await c.CountCurrentRevisionsAsync()).Should().Be(1); (await c.CountAdoptionsTotalAsync()).Should().Be(2); }
    [Fact] public async Task Staging_revision_is_not_current_before_adoption() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var r = await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); (await c.IsCurrentAsync(r.Value.OutputRevisionId!.Value)).Should().BeFalse(); }
    [Fact] public async Task Cancelled_run_does_not_leave_current_revision() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); var pending = await c.Coordinator.CreatePendingRunForTestAsync(c.DocumentInstanceId, p.Value.PresetId); await c.Coordinator.CancelRunAsync(pending.Value.OcrRunId); (await c.CountCurrentRevisionsAsync()).Should().Be(1); }
    [Fact] public async Task Ocr_run_does_not_create_search_units_or_evidence_refs() { await using var c = await OcrTestContext.CreateAsync(); var p = await c.CreatePresetAsync(); await c.Coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, p.Value.PresetId, [c.Pages[0].PageId]); await using var cn = c.Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); (await cn.ExecuteScalarAsync<int>("select count(1) from search_units;")).Should().Be(0); var tables = await c.TableNamesAsync(); tables.Should().NotContain("evidence_refs"); }
    [Fact] public async Task MigrationRunner_applies_ocr_lifecycle_migration() { await using var db = TemporarySqliteDatabase.Create(); await new MigrationRunner(db.ConnectionFactory, TestPaths.MigrationsDirectory).RunAsync(); await using var cn = db.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); var count = await cn.ExecuteScalarAsync<int>("select count(1) from sqlite_master where type='table' and name in ('ocr_presets','ocr_preset_versions','ocr_runs','ocr_page_results','ocr_candidate_adoptions');"); count.Should().Be(5); }
    [Fact] public async Task Foreign_keys_prevent_orphan_ocr_page_result() { await using var c = await OcrTestContext.CreateAsync(); await using var cn = c.Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); Func<Task> action = () => cn.ExecuteAsync("insert into ocr_page_results (result_id, ocr_run_id, page_id, state, created_at, updated_at) values (@Id, @Run, @Page, 'pending', @Now, @Now);", new { Id = OcrPageResultId.New().ToString(), Run = OcrRunId.New().ToString(), Page = PageId.New().ToString(), Now = DateTimeOffset.UtcNow.ToString("O") }); await action.Should().ThrowAsync<SqliteException>(); }

    private sealed class OcrTestContext : IAsyncDisposable
    {
        private OcrTestContext(TemporarySqliteDatabase database, DocumentInstanceId documentInstanceId, IReadOnlyList<Core.Layout.Page> pages, ItemService itemService, DocumentInstanceService documentInstanceService, PageService pageService, OcrPresetService presetService, OcrRunCoordinator coordinator, LayoutTreeService layoutTreeService) { Database = database; DocumentInstanceId = documentInstanceId; Pages = pages; ItemService = itemService; DocumentInstanceService = documentInstanceService; PageService = pageService; PresetService = presetService; Coordinator = coordinator; LayoutTreeService = layoutTreeService; }
        public TemporarySqliteDatabase Database { get; }
        public DocumentInstanceId DocumentInstanceId { get; }
        public IReadOnlyList<Core.Layout.Page> Pages { get; }
        public ItemService ItemService { get; }
        public DocumentInstanceService DocumentInstanceService { get; }
        public PageService PageService { get; }
        public OcrPresetService PresetService { get; }
        public OcrRunCoordinator Coordinator { get; }
        public LayoutTreeService LayoutTreeService { get; }
        public static async Task<OcrTestContext> CreateAsync()
        {
            var db = TemporarySqliteDatabase.Create(); var clock = new FixedClock(new DateTimeOffset(2026, 6, 19, 5, 0, 0, TimeSpan.Zero));
            await new MigrationRunner(db.ConnectionFactory, TestPaths.MigrationsDirectory).RunAsync();
            var lib = new LibraryIdentityService(db.ConnectionFactory, clock); await lib.CreateLibraryAsync("OCR library");
            var itemService = new ItemService(db.ConnectionFactory, lib, clock);
            var documentInstanceService = new DocumentInstanceService(db.ConnectionFactory, clock);
            var item = await itemService.CreateItemAsync("book", "OCR book");
            var doc = await documentInstanceService.AttachDocumentInstanceAsync(item.Value.ItemId, null, DocumentInstanceType.PrimaryScan);
            var pageSvc = new PageService(db.ConnectionFactory, clock); var pages = new List<Core.Layout.Page>();
            for (var i = 0; i < 3; i++) pages.Add((await pageSvc.CreatePageAsync(doc.Value.DocumentInstanceId, i, null, 100, 200, 0, CoordinateBasis.NormalizedPage, 100, 200, "renderer-v1", null)).Value);
            var layout = new LayoutTreeService(db.ConnectionFactory, clock); await layout.CreateLayoutRevisionAsync(doc.Value.DocumentInstanceId, LayoutRevisionSource.Mock, makeCurrent: true);
            var preset = new OcrPresetService(db.ConnectionFactory, lib, clock); var coordinator = new OcrRunCoordinator(db.ConnectionFactory, clock, new MockOcrEngine());
            return new OcrTestContext(db, doc.Value.DocumentInstanceId, pages, itemService, documentInstanceService, pageSvc, preset, coordinator, layout);
        }
        public Task<Result<OcrPreset>> CreatePresetAsync(bool apply = false, string parameters = "{}") => PresetService.CreatePresetAsync("Mock", null, OcrEngineIds.Mock, OcrModelIds.MockBasic, null, parameters, apply);
        public async Task<int> CountNodesAsync(LayoutRevisionId rev) { await using var cn = Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); return await cn.ExecuteScalarAsync<int>("select count(1) from layout_nodes where revision_id = @Rev;", new { Rev = rev.ToString() }); }
        public async Task<IReadOnlyList<PageId>> PageIdsWithNodesAsync(LayoutRevisionId rev) { await using var cn = Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); var ids = await cn.QueryAsync<string>("select distinct page_id from layout_nodes where revision_id = @Rev order by page_id;", new { Rev = rev.ToString() }); return ids.Select(PageId.Parse).ToArray(); }
        public async Task<int> CountAdoptionsAsync(OcrRunId run) { await using var cn = Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); return await cn.ExecuteScalarAsync<int>("select count(1) from ocr_candidate_adoptions where ocr_run_id = @Run;", new { Run = run.ToString() }); }
        public async Task<int> CountAdoptionsTotalAsync() { await using var cn = Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); return await cn.ExecuteScalarAsync<int>("select count(1) from ocr_candidate_adoptions;"); }
        public async Task<int> CountCurrentRevisionsAsync() { await using var cn = Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); return await cn.ExecuteScalarAsync<int>("select count(1) from layout_revisions where document_instance_id = @Doc and is_current = 1;", new { Doc = DocumentInstanceId.ToString() }); }
        public async Task<bool> IsCurrentAsync(LayoutRevisionId rev) { await using var cn = Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); return await cn.ExecuteScalarAsync<int>("select is_current from layout_revisions where layout_revision_id = @Rev;", new { Rev = rev.ToString() }) == 1; }
        public async Task<IReadOnlyList<string>> TableNamesAsync() { await using var cn = Database.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); return (await cn.QueryAsync<string>("select name from sqlite_master where type='table';")).ToArray(); }
        public ValueTask DisposeAsync() => Database.DisposeAsync();
    }
}
