using Dapper;
using FluentAssertions;
using Patchouli.Core.Bibliography;
using Patchouli.Core.Documents;
using Patchouli.Core.Ids;
using Patchouli.Core.Layout;
using Patchouli.Core.Results;
using Patchouli.Infrastructure.Bibliography;
using Patchouli.Infrastructure.Documents;
using Patchouli.Infrastructure.Layout;
using Patchouli.Infrastructure.LibraryIdentity;
using Patchouli.Infrastructure.Migrations;
using Patchouli.Infrastructure.Ocr;
using Patchouli.Infrastructure.Evidence;
using Patchouli.Infrastructure.Search;
using Patchouli.Evidence;
using Patchouli.Ocr;
using Patchouli.Search;
using Microsoft.Data.Sqlite;

namespace Patchouli.Tests;

public sealed class SearchTests
{
    [Fact] public async Task RebuildForDocumentInstance_creates_units_from_current_layout() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("alpha"); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.CountUnitsAsync()).Should().Be(1); }
    [Fact] public async Task RebuildForDocumentInstance_uses_current_revision_only() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("old"); var next = await c.LayoutTreeService.CreateLayoutRevisionAsync(c.DocumentInstanceId, LayoutRevisionSource.Manual, makeCurrent: true); c.RevisionId = next.Value.LayoutRevisionId; await c.AddNodeAsync("new"); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.UnitTextsAsync()).Should().Equal("new"); }
    [Fact] public async Task SearchUnit_excludes_ignored_nodes() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("hidden", ignored: true); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.CountUnitsAsync()).Should().Be(0); }
    [Fact] public async Task SearchUnit_excludes_header_footer_page_number() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("h", LayoutNodeType.Header); await c.AddNodeAsync("f", LayoutNodeType.Footer); await c.AddNodeAsync("1", LayoutNodeType.PageNumber); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.CountUnitsAsync()).Should().Be(0); }
    [Fact] public async Task SearchUnit_excludes_marginalia_annotation_by_default() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("m", LayoutNodeType.Marginalia); await c.AddNodeAsync("a", LayoutNodeType.Annotation); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.CountUnitsAsync()).Should().Be(0); }
    [Fact] public async Task TextPolicy_own_creates_unit() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("own", textPolicy: TextPolicy.Own); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.UnitTextsAsync()).Should().Contain("own"); }
    [Fact] public async Task TextPolicy_aggregate_children_creates_aggregated_unit() { await using var c = await SearchTestContext.CreateAsync(); var parent = await c.AddNodeAsync(null, LayoutNodeType.Block, TextPolicy.AggregateChildren); await c.AddNodeAsync("child one", parentNodeId: parent.Value.NodeId); await c.AddNodeAsync("child two", parentNodeId: parent.Value.NodeId, readingOrder: 2); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.UnitTextsAsync()).Should().Contain(t => t.Contains("child one") && t.Contains("child two")); (await c.CountUnitsAsync()).Should().Be(1); }
    [Fact] public async Task TextPolicy_none_creates_no_unit() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("none", textPolicy: TextPolicy.None); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.CountUnitsAsync()).Should().Be(0); }
    [Fact] public async Task Table_degrades_without_duplicate_child_indexing() { await using var c = await SearchTestContext.CreateAsync(); var table = await c.AddNodeAsync(null, LayoutNodeType.Table, TextPolicy.AggregateChildren); await c.AddNodeAsync("cell text", LayoutNodeType.TableCell, parentNodeId: table.Value.NodeId); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.UnitTextsAsync()).Should().Equal("[Table]"); }
    [Fact] public async Task Rebuild_preserves_unit_id_for_text_edit_same_node_revision() { await using var c = await SearchTestContext.CreateAsync(); var node = await c.AddNodeAsync("before"); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); var first = await c.UnitIdsAsync(); await c.LayoutTreeService.UpdateNodeTextAsync(node.Value.NodeId, "after"); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.UnitIdsAsync()).Should().Equal(first); (await c.UnitTextsAsync()).Should().Equal("after"); }
    [Fact] public async Task Rebuild_links_evidence_successor_when_new_revision_replaces_unit() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("before"); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); var evidence = new EvidenceReferenceService(c.Database.ConnectionFactory, c.Clock); var oldRef = await evidence.CreateFromSearchUnitAsync(SearchUnitId.Parse((await c.UnitIdsAsync()).Single())); var next = await c.LayoutTreeService.CreateLayoutRevisionAsync(c.DocumentInstanceId, LayoutRevisionSource.OcrAdopted, makeCurrent: true); c.RevisionId = next.Value.LayoutRevisionId; await c.AddNodeAsync("after"); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); var pinned = await evidence.ResolveAsync(oldRef.Value.EvidenceRefId); var current = await evidence.ResolveAsync(oldRef.Value.EvidenceRefId, EvidenceResolutionMode.Current); pinned.Value.Status.Should().Be(EvidenceResolutionStatus.Superseded); pinned.Value.SuccessorEvidenceRefs.Should().HaveCount(1); current.Value.Status.Should().Be(EvidenceResolutionStatus.FoundCurrent); current.Value.CurrentText.Should().Be("after"); (await c.UnitTextsAsync()).Should().Equal("after"); }
    [Fact] public async Task Deleted_or_no_longer_indexable_node_marks_unit_deleted_or_stale() { await using var c = await SearchTestContext.CreateAsync(); var node = await c.AddNodeAsync("gone"); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); await c.LayoutTreeService.UpdateNodeTextAsync(node.Value.NodeId, " "); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.CountUnitsByStatusAsync(SearchUnitStatus.Deleted)).Should().Be(1); }
    [Fact] public async Task Bbox_union_is_recorded() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("box", bbox: new NormalizedBBox(0.1, 0.2, 0.3, 0.4)); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); (await c.Connection().ExecuteScalarAsync<string>("select bbox_union_json from search_units limit 1;")).Should().Contain("0.1"); }
    [Fact] public async Task RebuildFtsForDocumentInstance_populates_fts() { await using var c = await SearchTestContext.CreateWithUnitAsync("latin alpha"); await c.Rebuilder.RebuildFtsForDocumentInstanceAsync(c.DocumentInstanceId); (await c.CountFtsAsync()).Should().Be(1); }
    [Fact] public async Task RebuildFtsForLibrary_populates_all_current_units() { await using var c = await SearchTestContext.CreateWithUnitAsync("latin alpha"); await c.Rebuilder.RebuildFtsForLibraryAsync(); (await c.CountFtsAsync()).Should().Be(1); }
    [Fact] public async Task RebuildFts_marks_index_status_current() { await using var c = await SearchTestContext.CreateWithUnitAsync("latin alpha"); await c.Rebuilder.RebuildFtsForDocumentInstanceAsync(c.DocumentInstanceId); (await c.StatusAsync(SearchIndexScopeType.DocumentInstance, c.DocumentInstanceId.ToString())).Should().Be(SearchIndexStatusValue.Current); }
    [Fact] public async Task MarkDocumentInstanceDirty_sets_stale_status() { await using var c = await SearchTestContext.CreateAsync(); await c.Builder.MarkDocumentInstanceDirtyAsync(c.DocumentInstanceId); (await c.StatusAsync(SearchIndexScopeType.DocumentInstance, c.DocumentInstanceId.ToString())).Should().Be(SearchIndexStatusValue.Stale); }
    [Fact] public async Task SetIndexUnavailable_causes_search_to_return_empty_without_fallback() { await using var c = await SearchTestContext.CreateWithUnitAsync("only in units"); await c.Rebuilder.SetIndexUnavailableAsync(SearchIndexScopeType.Library, c.LibraryId.ToString(), "fts unavailable"); var result = await c.Search.SearchLibraryAsync(new SearchRequest("only")); result.Value.Results.Should().BeEmpty(); result.Value.AffectedScopesSummary.Should().Be("fts unavailable"); }
    [Fact] public async Task SearchLibrary_rejects_blank_query() { await using var c = await SearchTestContext.CreateAsync(); (await c.Search.SearchLibraryAsync(new SearchRequest(" "))).ErrorCode.Should().Be(AppErrorCodes.ValidationFailed); }
    [Fact] public async Task SearchLibrary_returns_page_level_results() { await using var c = await SearchTestContext.CreateWithUnitAsync("latin alpha"); await c.Rebuilder.RebuildFtsForLibraryAsync(); var result = await c.Search.SearchLibraryAsync(new SearchRequest("alpha")); result.Value.Results.Single().PageId.Should().Be(c.PageId); }
    [Fact] public async Task SearchLibrary_groups_multiple_units_by_page() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("alpha one"); await c.AddNodeAsync("alpha two", readingOrder: 2); await c.RebuildAllAsync(); var result = await c.Search.SearchLibraryAsync(new SearchRequest("alpha")); result.Value.Results.Should().HaveCount(1); result.Value.Results.Single().MatchedUnits.Should().HaveCount(2); }
    [Fact] public async Task SearchLibrary_limits_matched_units_per_page_to_5() { await using var c = await SearchTestContext.CreateAsync(); for (var i = 0; i < 6; i++) await c.AddNodeAsync($"alpha {i}", readingOrder: i); await c.RebuildAllAsync(); var result = await c.Search.SearchLibraryAsync(new SearchRequest("alpha")); result.Value.Results.Single().MatchedUnits.Should().HaveCount(5); result.Value.Results.Single().MatchedUnitsHasMore.Should().BeTrue(); }
    [Fact] public async Task SearchLibrary_supports_page_size_and_cursor() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("alpha p0"); var p1 = await c.CreatePageAsync(1); await c.AddNodeAsync("alpha p1", pageId: p1.Value.PageId); var p2 = await c.CreatePageAsync(2); await c.AddNodeAsync("alpha p2", pageId: p2.Value.PageId); await c.RebuildAllAsync(); var first = await c.Search.SearchLibraryAsync(new SearchRequest("alpha", PageSize: 1)); var second = await c.Search.SearchLibraryAsync(new SearchRequest("alpha", PageSize: 1, Cursor: first.Value.NextCursor)); first.Value.Results.Should().HaveCount(1); second.Value.Results.Should().HaveCount(1); second.Value.Results.Single().PageId.Should().NotBe(first.Value.Results.Single().PageId); }
    [Fact] public async Task SearchLibrary_returns_partial_or_stale_index_status() { await using var c = await SearchTestContext.CreateWithUnitAsync("alpha"); await c.Rebuilder.RebuildFtsForLibraryAsync(); await c.Builder.MarkDocumentInstanceDirtyAsync(c.DocumentInstanceId); var result = await c.Search.SearchLibraryAsync(new SearchRequest("alpha")); result.Value.IndexStatus.Should().Be(SearchIndexStatusValue.Stale); result.Value.Results.Should().NotBeEmpty(); }
    [Fact] public async Task SearchLibrary_does_not_return_evidence_ref() { typeof(SearchMatchedUnit).GetProperties().Select(p => p.Name).Should().NotContain(name => name.Contains("Evidence", StringComparison.OrdinalIgnoreCase)); }
    [Fact] public async Task SearchLibrary_can_find_chinese_text() { await using var c = await SearchTestContext.CreateWithUnitAsync("这是 OCR 测试文本。"); await c.Rebuilder.RebuildFtsForLibraryAsync(); (await c.Search.SearchLibraryAsync(new SearchRequest("测试"))).Value.Results.Should().NotBeEmpty(); }
    [Fact] public async Task SearchLibrary_can_find_latin_text() { await using var c = await SearchTestContext.CreateWithUnitAsync("Latin archive keyword"); await c.Rebuilder.RebuildFtsForLibraryAsync(); (await c.Search.SearchLibraryAsync(new SearchRequest("archive"))).Value.Results.Should().NotBeEmpty(); }
    [Fact] public async Task SearchLibrary_filters_by_document_instance_when_requested() { await using var c = await SearchTestContext.CreateWithUnitAsync("alpha"); var other = await c.CreateDocumentInstanceAsync("Other"); var page = await c.PageService.CreatePageAsync(other, 0, null, null, null, 0, CoordinateBasis.NormalizedPage, null, null, "renderer-v1", null); var rev = await c.LayoutTreeService.CreateLayoutRevisionAsync(other, LayoutRevisionSource.Mock, makeCurrent: true); await c.LayoutTreeService.AddNodeAsync(rev.Value.LayoutRevisionId, page.Value.PageId, null, LayoutNodeType.Paragraph, null, "alpha", TextPolicy.Own, 1, LayoutNodeSource.Mock); await c.Builder.RebuildForDocumentInstanceAsync(other); await c.Rebuilder.RebuildFtsForLibraryAsync(); var result = await c.Search.SearchLibraryAsync(new SearchRequest("alpha", DocumentInstanceId: c.DocumentInstanceId)); result.Value.Results.Should().OnlyContain(r => r.DocumentInstanceId == c.DocumentInstanceId); }
    [Fact] public async Task GetSearchResultContext_returns_sibling_units() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("before", readingOrder: 1); await c.AddNodeAsync("match", readingOrder: 2); await c.AddNodeAsync("after", readingOrder: 3); await c.RebuildAllAsync(); var id = (await c.UnitIdsAsync())[1]; var ctx = await c.Search.GetSearchResultContextAsync(SearchUnitId.Parse(id)); ctx.Value.Select(u => u.Text).Should().Equal("before", "match", "after"); }
    [Fact] public async Task GetSearchResultContext_does_not_cross_page() { await using var c = await SearchTestContext.CreateAsync(); await c.AddNodeAsync("same"); var p = await c.CreatePageAsync(1); await c.AddNodeAsync("other", pageId: p.Value.PageId); await c.RebuildAllAsync(); await using var cn = c.Connection(); var id = await cn.ExecuteScalarAsync<string>("select unit_id from search_units where resolved_text = 'same';"); var ctx = await c.Search.GetSearchResultContextAsync(SearchUnitId.Parse(id!), 10, 10); ctx.Value.Should().OnlyContain(u => u.PageId == c.PageId); }
    [Fact] public async Task GetSearchResultContext_caps_before_after_at_10() { await using var c = await SearchTestContext.CreateAsync(); for (var i = 0; i < 30; i++) await c.AddNodeAsync($"u{i}", readingOrder: i); await c.RebuildAllAsync(); var id = (await c.UnitIdsAsync())[15]; var ctx = await c.Search.GetSearchResultContextAsync(SearchUnitId.Parse(id), 99, 99); ctx.Value.Should().HaveCount(21); }
    [Fact] public async Task GetSearchResultContext_marks_match_unit() { await using var c = await SearchTestContext.CreateWithUnitAsync("match"); var id = (await c.UnitIdsAsync()).Single(); var ctx = await c.Search.GetSearchResultContextAsync(SearchUnitId.Parse(id)); ctx.Value.Single().IsMatch.Should().BeTrue(); }
    [Fact] public async Task MigrationRunner_applies_search_migration() { await using var db = TemporarySqliteDatabase.Create(); await new MigrationRunner(db.ConnectionFactory, TestPaths.MigrationsDirectory).RunAsync(); await using var cn = db.ConnectionFactory.CreateConnection(); await cn.OpenAsync(); (await cn.ExecuteScalarAsync<int>("select count(1) from sqlite_master where name in ('search_units','search_index_status','search_units_fts');")).Should().Be(3); }
    [Fact] public async Task FTS5_table_is_created_and_queryable() { await using var c = await SearchTestContext.CreateWithUnitAsync("alpha"); await c.Rebuilder.RebuildFtsForLibraryAsync(); (await c.Connection().ExecuteScalarAsync<int>("select count(1) from search_units_fts where search_units_fts match 'alpha';")).Should().Be(1); }
    [Fact] public async Task Foreign_keys_prevent_orphan_search_unit() { await using var c = await SearchTestContext.CreateAsync(); var act = async () => await c.Connection().ExecuteAsync("insert into search_units (unit_id, document_instance_id, page_id, root_node_id, text_revision_id, bbox_revision_id, layout_revision_id, resolved_text, node_type, reading_order, status, created_at, updated_at) values (@Id, @Doc, @Page, @Node, @Rev, @Rev, @Rev, 'x', 'paragraph', 1, 'current', @Now, @Now);", new { Id = SearchUnitId.New().ToString(), Doc = DocumentInstanceId.New().ToString(), Page = PageId.New().ToString(), Node = LayoutNodeId.New().ToString(), Rev = LayoutRevisionId.New().ToString(), Now = DateTimeOffset.UtcNow.ToString("O") }); await act.Should().ThrowAsync<SqliteException>(); }
    [Fact] public async Task Search_does_not_use_SQL_LIKE_when_fts_unavailable() { await using var c = await SearchTestContext.CreateWithUnitAsync("not in fts fallback text"); await c.Rebuilder.SetIndexUnavailableAsync(SearchIndexScopeType.Library, c.LibraryId.ToString(), "off"); var result = await c.Search.SearchLibraryAsync(new SearchRequest("fallback")); result.Value.Results.Should().BeEmpty(); }
    [Fact] public async Task Ocr_adoption_marks_document_instance_dirty_when_marker_is_configured() { await using var c = await SearchTestContext.CreateAsync(); var library = new LibraryIdentityService(c.Database.ConnectionFactory, c.Clock); var preset = new OcrPresetService(c.Database.ConnectionFactory, library, c.Clock); var created = await preset.CreatePresetAsync("mock", null, OcrEngineIds.Mock, OcrModelIds.MockBasic, null, "{}", true); var coordinator = new OcrRunCoordinator(c.Database.ConnectionFactory, c.Clock, searchDirtyMarker: c.Builder); await coordinator.RunPresetOnPagesAsync(c.DocumentInstanceId, created.Value.PresetId, [c.PageId]); (await c.StatusAsync(SearchIndexScopeType.DocumentInstance, c.DocumentInstanceId.ToString())).Should().Be(SearchIndexStatusValue.Stale); }

    private sealed class SearchTestContext : IAsyncDisposable
    {
        private SearchTestContext(TemporarySqliteDatabase database, FixedClock clock, LibraryId libraryId, ItemId itemId, DocumentInstanceId documentInstanceId, PageId pageId, LayoutRevisionId revisionId)
        {
            Database = database; Clock = clock; LibraryId = libraryId; ItemId = itemId; DocumentInstanceId = documentInstanceId; PageId = pageId; RevisionId = revisionId;
            PageService = new PageService(database.ConnectionFactory, clock);
            LayoutTreeService = new LayoutTreeService(database.ConnectionFactory, clock);
            Builder = new SearchUnitBuilder(database.ConnectionFactory, clock);
            Rebuilder = new SearchIndexRebuilder(database.ConnectionFactory, clock);
            Search = new SqliteSearchService(database.ConnectionFactory);
        }
        public TemporarySqliteDatabase Database { get; }
        public FixedClock Clock { get; }
        public LibraryId LibraryId { get; }
        public ItemId ItemId { get; }
        public DocumentInstanceId DocumentInstanceId { get; }
        public PageId PageId { get; }
        public LayoutRevisionId RevisionId { get; set; }
        public PageService PageService { get; }
        public LayoutTreeService LayoutTreeService { get; }
        public SearchUnitBuilder Builder { get; }
        public SearchIndexRebuilder Rebuilder { get; }
        public SqliteSearchService Search { get; }
        public static async Task<SearchTestContext> CreateAsync()
        {
            var db = TemporarySqliteDatabase.Create(); var clock = new FixedClock(DateTimeOffset.Parse("2026-01-01T00:00:00Z"));
            await new MigrationRunner(db.ConnectionFactory, TestPaths.MigrationsDirectory).RunAsync();
            var library = await new LibraryIdentityService(db.ConnectionFactory, clock).CreateLibraryAsync("Search Library");
            var item = await new ItemService(db.ConnectionFactory, new LibraryIdentityService(db.ConnectionFactory, clock), clock).CreateItemAsync("book", "Search Item");
            var doc = await new DocumentInstanceService(db.ConnectionFactory, clock).AttachDocumentInstanceAsync(item.Value.ItemId, null, DocumentInstanceType.PrimaryScan);
            var pageService = new PageService(db.ConnectionFactory, clock);
            var page = await pageService.CreatePageAsync(doc.Value.DocumentInstanceId, 0, "1", null, null, 0, CoordinateBasis.NormalizedPage, null, null, "renderer-v1", null);
            var layout = new LayoutTreeService(db.ConnectionFactory, clock);
            var revision = await layout.CreateLayoutRevisionAsync(doc.Value.DocumentInstanceId, LayoutRevisionSource.Mock, makeCurrent: true);
            return new SearchTestContext(db, clock, library.Value.LibraryId, item.Value.ItemId, doc.Value.DocumentInstanceId, page.Value.PageId, revision.Value.LayoutRevisionId);
        }
        public static async Task<SearchTestContext> CreateWithUnitAsync(string text) { var c = await CreateAsync(); await c.AddNodeAsync(text); await c.Builder.RebuildForDocumentInstanceAsync(c.DocumentInstanceId); return c; }
        public async Task<Result<Core.Layout.Page>> CreatePageAsync(int index) => await PageService.CreatePageAsync(DocumentInstanceId, index, (index + 1).ToString(), null, null, 0, CoordinateBasis.NormalizedPage, null, null, "renderer-v1", null);
        public async Task<DocumentInstanceId> CreateDocumentInstanceAsync(string title)
        {
            var item = await new ItemService(Database.ConnectionFactory, new LibraryIdentityService(Database.ConnectionFactory, Clock), Clock).CreateItemAsync("book", title);
            var doc = await new DocumentInstanceService(Database.ConnectionFactory, Clock).AttachDocumentInstanceAsync(item.Value.ItemId, null, DocumentInstanceType.AlternateScan);
            return doc.Value.DocumentInstanceId;
        }
        public async Task<Result<LayoutNode>> AddNodeAsync(string? text, string nodeType = LayoutNodeType.Paragraph, string textPolicy = TextPolicy.Own, int readingOrder = 1, PageId? pageId = null, LayoutNodeId? parentNodeId = null, NormalizedBBox? bbox = null, bool ignored = false)
            => await LayoutTreeService.AddNodeAsync(RevisionId, pageId ?? PageId, parentNodeId, nodeType, bbox, text, textPolicy, readingOrder, LayoutNodeSource.Mock, ignored: ignored);
        public async Task RebuildAllAsync() { await Builder.RebuildForDocumentInstanceAsync(DocumentInstanceId); await Rebuilder.RebuildFtsForLibraryAsync(); }
        public SqliteConnection Connection() { var c = Database.ConnectionFactory.CreateConnection(); c.Open(); return c; }
        public async Task<int> CountUnitsAsync() { await using var cn = Connection(); return await cn.ExecuteScalarAsync<int>("select count(1) from search_units where status = 'current';"); }
        public async Task<int> CountUnitsByStatusAsync(string status) { await using var cn = Connection(); return await cn.ExecuteScalarAsync<int>("select count(1) from search_units where status = @Status;", new { Status = status }); }
        public async Task<int> CountFtsAsync() { await using var cn = Connection(); return await cn.ExecuteScalarAsync<int>("select count(1) from search_units_fts;"); }
        public async Task<string[]> UnitTextsAsync() { await using var cn = Connection(); return (await cn.QueryAsync<string>("select resolved_text from search_units where status = 'current' order by reading_order, unit_id;")).ToArray(); }
        public async Task<string[]> UnitIdsAsync() { await using var cn = Connection(); return (await cn.QueryAsync<string>("select unit_id from search_units where status = 'current' order by page_id, reading_order, unit_id;")).ToArray(); }
        public async Task<string?> StatusAsync(string scopeType, string scopeId) { await using var cn = Connection(); return await cn.ExecuteScalarAsync<string?>("select status from search_index_status where scope_type = @ScopeType and scope_id = @ScopeId;", new { ScopeType = scopeType, ScopeId = scopeId }); }
        public ValueTask DisposeAsync() => Database.DisposeAsync();
    }
}
